//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epcdhackthon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Form_Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Form_Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("epcdhackthon.Resources.Views.Form.Index", typeof(Views_Form_Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموافقة على الشروط والاحكام.
        /// </summary>
        internal static string conditions1 {
            get {
                return ResourceManager.GetString("conditions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموافقة على التصوير والنشر على وسائل التواصل الاجتماعي.
        /// </summary>
        internal static string conditions2 {
            get {
                return ResourceManager.GetString("conditions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل الشخصية لقائد الفريق.
        /// </summary>
        internal static string formSubSextion1 {
            get {
                return ResourceManager.GetString("formSubSextion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الفكرة والفريق.
        /// </summary>
        internal static string formSubSextion2 {
            get {
                return ResourceManager.GetString("formSubSextion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج التسجيل.
        /// </summary>
        internal static string formTitle {
            get {
                return ResourceManager.GetString("formTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفكرة.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفريق.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        internal static string labelDate1 {
            get {
                return ResourceManager.GetString("labelDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  البريد الالكتروني.
        /// </summary>
        internal static string labelEmail {
            get {
                return ResourceManager.GetString("labelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل باللغة العربية.
        /// </summary>
        internal static string labelName1 {
            get {
                return ResourceManager.GetString("labelName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل باللغة الانجليزية.
        /// </summary>
        internal static string labelName2 {
            get {
                return ResourceManager.GetString("labelName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الفكرة.
        /// </summary>
        internal static string labelName3 {
            get {
                return ResourceManager.GetString("labelName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        internal static string labelName4 {
            get {
                return ResourceManager.GetString("labelName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        internal static string labelNat {
            get {
                return ResourceManager.GetString("labelNat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        internal static string labelPhone {
            get {
                return ResourceManager.GetString("labelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صنـاعـــــــة وحيـــــــاة.
        /// </summary>
        internal static string slogen {
            get {
                return ResourceManager.GetString("slogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
    }
}
