//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epcdhackthon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home_Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home_Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("epcdhackthon.Resources.Views.Home.Index.en", typeof(Views_Home_Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Royal Commission&apos;s Environmental Hackathon aims to promote innovative environmental solutions and enhance sustainability practices across industries under the Royal Commission. This is achieved through collaborative problem-solving and the use of modern technologies to provide environmental solutions to existing issues.
        /// </summary>
        internal static string aboutText1 {
            get {
                return ResourceManager.GetString("aboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hackathon presents a unique opportunity for creators and innovators from various fields to collaborate on developing effective and sustainable environmental solutions. By bringing together creative minds and diverse expertise, we aim to find new and innovative solutions to the environmental challenges faced by different industries.
        /// </summary>
        internal static string aboutText2 {
            get {
                return ResourceManager.GetString("aboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string aboutTitle {
            get {
                return ResourceManager.GetString("aboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team leader must be of Saudi nationality..
        /// </summary>
        internal static string condition1 {
            get {
                return ResourceManager.GetString("condition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Requirements.
        /// </summary>
        internal static string conditionsTitle {
            get {
                return ResourceManager.GetString("conditionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string dayCounter {
            get {
                return ResourceManager.GetString("dayCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the hackathon.
        /// </summary>
        internal static string formLink {
            get {
                return ResourceManager.GetString("formLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By encouraging participants to exchange ideas and experiences, we can achieve greater integration between different industries and realize mutual benefits.
        /// </summary>
        internal static string goalsSubText1 {
            get {
                return ResourceManager.GetString("goalsSubText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We aim to develop solutions that can be practically implemented across various industries, contributing to improved environmental performance and reducing negative environmental impact.
        /// </summary>
        internal static string goalsSubText2 {
            get {
                return ResourceManager.GetString("goalsSubText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By presenting innovative solutions, we can accelerate the adoption of sustainable practices across various industries, contributing to the achievement of long-term sustainability goals.
        /// </summary>
        internal static string goalsSubText3 {
            get {
                return ResourceManager.GetString("goalsSubText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By organizing this hackathon, we reaffirm the Royal Commission&apos;s commitment to supporting environmental innovation and promoting sustainable practices. This initiative highlights our dedication to fostering an environment where creative solutions can thrive and sustainability can be integrated into various industries.
        /// </summary>
        internal static string goalsSubText4 {
            get {
                return ResourceManager.GetString("goalsSubText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developing practical and implementable solutions..
        /// </summary>
        internal static string goalsSubTitle2 {
            get {
                return ResourceManager.GetString("goalsSubTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerating the adoption of sustainable practices..
        /// </summary>
        internal static string goalsSubTitle3 {
            get {
                return ResourceManager.GetString("goalsSubTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighting the Royal Commission&apos;s commitment to environmental preservation.
        /// </summary>
        internal static string goalsSubTitle4 {
            get {
                return ResourceManager.GetString("goalsSubTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying and nurturing talent in the field of environmental innovation.
        /// </summary>
        internal static string goalsSubTitle5 {
            get {
                return ResourceManager.GetString("goalsSubTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hackathon provides an opportunity to discover and support new talents, contributing to the development of a new generation of environmental innovators. By offering a platform for creative minds to showcase their ideas and collaborate with industry experts, we aim to nurture the skills and potential of emerging talents, ultimately fostering a community dedicated to solving environmental challenges.
        /// </summary>
        internal static string goalsSubTitle6 {
            get {
                return ResourceManager.GetString("goalsSubTitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackathon Goals.
        /// </summary>
        internal static string goalsTitle {
            get {
                return ResourceManager.GetString("goalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fostering collaboration among various industries..
        /// </summary>
        internal static string goalSubTitle1 {
            get {
                return ResourceManager.GetString("goalSubTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration ends after.
        /// </summary>
        internal static string headerSubTitle {
            get {
                return ResourceManager.GetString("headerSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental Hackathon 2024.
        /// </summary>
        internal static string headerTitle {
            get {
                return ResourceManager.GetString("headerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental Hackathon.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string hoursCounter {
            get {
                return ResourceManager.GetString("hoursCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutescounter {
            get {
                return ResourceManager.GetString("minutescounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Riyals.
        /// </summary>
        internal static string prizeCurrency {
            get {
                return ResourceManager.GetString("prizeCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For winners and finalists, as well as post-hackathon training and development opportunities..
        /// </summary>
        internal static string prizeSubTitle {
            get {
                return ResourceManager.GetString("prizeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total prize money is more than.
        /// </summary>
        internal static string prizeTitle {
            get {
                return ResourceManager.GetString("prizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved 2024, Royal Commission for Jubail and Yanbu..
        /// </summary>
        internal static string rights {
            get {
                return ResourceManager.GetString("rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string roadmapElement1 {
            get {
                return ResourceManager.GetString("roadmapElement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Workshops.
        /// </summary>
        internal static string roadmapElement2 {
            get {
                return ResourceManager.GetString("roadmapElement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifiers Announcement.
        /// </summary>
        internal static string roadmapElement3 {
            get {
                return ResourceManager.GetString("roadmapElement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarding Session.
        /// </summary>
        internal static string roadmapElement4 {
            get {
                return ResourceManager.GetString("roadmapElement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Judging.
        /// </summary>
        internal static string roadmapElement5 {
            get {
                return ResourceManager.GetString("roadmapElement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Ceremony.
        /// </summary>
        internal static string roadmapElement6 {
            get {
                return ResourceManager.GetString("roadmapElement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts.
        /// </summary>
        internal static string roadmapLabel {
            get {
                return ResourceManager.GetString("roadmapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends.
        /// </summary>
        internal static string roadmapLabel1 {
            get {
                return ResourceManager.GetString("roadmapLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackathon Journey.
        /// </summary>
        internal static string roadmapTitle {
            get {
                return ResourceManager.GetString("roadmapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string secondsCounter {
            get {
                return ResourceManager.GetString("secondsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to industry and Life.
        /// </summary>
        internal static string slogen {
            get {
                return ResourceManager.GetString("slogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrochemicals.
        /// </summary>
        internal static string target1 {
            get {
                return ResourceManager.GetString("target1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minerals and Mining.
        /// </summary>
        internal static string target2 {
            get {
                return ResourceManager.GetString("target2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing .
        /// </summary>
        internal static string target3 {
            get {
                return ResourceManager.GetString("target3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All industries at the RC-Yanbu.
        /// </summary>
        internal static string target4 {
            get {
                return ResourceManager.GetString("target4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Audience.
        /// </summary>
        internal static string targetTitle {
            get {
                return ResourceManager.GetString("targetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Efficiency
        ///
        ///.
        /// </summary>
        internal static string track1 {
            get {
                return ResourceManager.GetString("track1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Management
        ///
        ///.
        /// </summary>
        internal static string track2 {
            get {
                return ResourceManager.GetString("track2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Treatment.
        /// </summary>
        internal static string track3 {
            get {
                return ResourceManager.GetString("track3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hackathon Tracks.
        /// </summary>
        internal static string tracksTitle {
            get {
                return ResourceManager.GetString("tracksTitle", resourceCulture);
            }
        }
    }
}
