//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epcdhackthon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home_Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home_Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("epcdhackthon.Resources.Views.Home.Index", typeof(Views_Home_Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يهدف هاكاثون البيئية للهيئة الملكية إلى تعزيز الحلول البيئية المبتكرة وتحسين ممارسات الاستدامة عبر الصناعات التابعة للهيئة الملكية من خلال حل المشكلات بشكل تعاوني واستخدام التقنيات
        ///الحديثة لتقديم حلول بيئية للمشكلات القائمة..
        /// </summary>
        internal static string aboutText1 {
            get {
                return ResourceManager.GetString("aboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يُعد هذا الهاكاثون فرصة فريدة للمبدعين والمبتكرين من مختلف المجالات للعمل معًا على تطوير حلول بيئية
        ///فعّالة ومستدامة. من خلال الجمع بين العقول المبدعة والخبرات المتنوعة، نسعى إلى إيجاد حلول جديدة
        ///ومبتكرة للتحديات البيئية التي تواجه الصناعات المختلفة..
        /// </summary>
        internal static string aboutText2 {
            get {
                return ResourceManager.GetString("aboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن هاكاثون البيئة.
        /// </summary>
        internal static string aboutTitle {
            get {
                return ResourceManager.GetString("aboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أن يكون قائد الفريق سعودي الجنسية..
        /// </summary>
        internal static string condition1 {
            get {
                return ResourceManager.GetString("condition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط التسجيل.
        /// </summary>
        internal static string conditionsTitle {
            get {
                return ResourceManager.GetString("conditionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم.
        /// </summary>
        internal static string dayCounter {
            get {
                return ResourceManager.GetString("dayCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انضم للهاكاثون.
        /// </summary>
        internal static string formLink {
            get {
                return ResourceManager.GetString("formLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من خلال تشجيع المشاركين على تبادل الأفكار والخبرات، يمكننا تحقيق تكامل أكبر بين الصناعات المختلفة
        ///وتحقيق فوائد مشتركة..
        /// </summary>
        internal static string goalsSubText1 {
            get {
                return ResourceManager.GetString("goalsSubText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسعى إلى تطوير حلول يمكن تطبيقها بشكل فعلي في الصناعات المختلفة، مما يسهم في تحسين الأداء البيئي
        ///وتقليل الأثر البيئي السلبي..
        /// </summary>
        internal static string goalsSubText2 {
            get {
                return ResourceManager.GetString("goalsSubText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من خلال تقديم حلول مبتكرة، يمكننا تسريع عملية تبني الممارسات المستدامة في الصناعات المختلفة، مما
        ///يسهم في تحقيق أهداف الاستدامة على المدى الطويل..
        /// </summary>
        internal static string goalsSubText3 {
            get {
                return ResourceManager.GetString("goalsSubText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من خلال تنظيم هذا الهاكاثون، نؤكد على التزام الهيئة الملكية بدعم الابتكار البيئي وتعزيز ممارسات
        ///الاستدامة..
        /// </summary>
        internal static string goalsSubText4 {
            get {
                return ResourceManager.GetString("goalsSubText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطوير حلول عملية وقابلة للتنفيذ.
        /// </summary>
        internal static string goalsSubTitle2 {
            get {
                return ResourceManager.GetString("goalsSubTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسريع تبني الممارسات المستدامة
        ///.
        /// </summary>
        internal static string goalsSubTitle3 {
            get {
                return ResourceManager.GetString("goalsSubTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إبراز التزام الهيئة الملكية بالحفاظ على البيئة.
        /// </summary>
        internal static string goalsSubTitle4 {
            get {
                return ResourceManager.GetString("goalsSubTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد ورعاية المواهب في مجال الابتكار البيئي.
        /// </summary>
        internal static string goalsSubTitle5 {
            get {
                return ResourceManager.GetString("goalsSubTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتيح الهاكاثون الفرصة لاكتشاف المواهب الجديدة ودعمها، مما يسهم في تطوير جيل جديد من المبتكرين
        ///البيئيين..
        /// </summary>
        internal static string goalsSubTitle6 {
            get {
                return ResourceManager.GetString("goalsSubTitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أهداف الهاكاثون.
        /// </summary>
        internal static string goalsTitle {
            get {
                return ResourceManager.GetString("goalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعزيز التعاون بين الصناعات المختلفة
        ///.
        /// </summary>
        internal static string goalSubTitle1 {
            get {
                return ResourceManager.GetString("goalSubTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ينتهي التسجيل بعد.
        /// </summary>
        internal static string headerSubTitle {
            get {
                return ResourceManager.GetString("headerSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاكثون البيئة 2024.
        /// </summary>
        internal static string headerTitle {
            get {
                return ResourceManager.GetString("headerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاكثون البيئة.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الساعات.
        /// </summary>
        internal static string hoursCounter {
            get {
                return ResourceManager.GetString("hoursCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدقائق.
        /// </summary>
        internal static string minutescounter {
            get {
                return ResourceManager.GetString("minutescounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريال سعودي.
        /// </summary>
        internal static string prizeCurrency {
            get {
                return ResourceManager.GetString("prizeCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للفائزين والمشاركين في المرحلة النهائية بالإضافة إلى فرص تدريبية وتطويرية ما بعد الهاكاثون.
        /// </summary>
        internal static string prizeSubTitle {
            get {
                return ResourceManager.GetString("prizeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الجوائز المالية أكثر من.
        /// </summary>
        internal static string prizeTitle {
            get {
                return ResourceManager.GetString("prizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                جميع الحقوق محفوظة 2024، الهيئه الملكيه للجبيل وينبع..
        /// </summary>
        internal static string rights {
            get {
                return ResourceManager.GetString("rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        internal static string roadmapElement1 {
            get {
                return ResourceManager.GetString("roadmapElement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورش العمل الافتراضية.
        /// </summary>
        internal static string roadmapElement2 {
            get {
                return ResourceManager.GetString("roadmapElement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورش العمل الافتراضية.
        /// </summary>
        internal static string roadmapElement3 {
            get {
                return ResourceManager.GetString("roadmapElement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الورشة التحضيرية.
        /// </summary>
        internal static string roadmapElement4 {
            get {
                return ResourceManager.GetString("roadmapElement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحكيم النهائي.
        /// </summary>
        internal static string roadmapElement5 {
            get {
                return ResourceManager.GetString("roadmapElement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحفل الختامي.
        /// </summary>
        internal static string roadmapElement6 {
            get {
                return ResourceManager.GetString("roadmapElement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإطلاق.
        /// </summary>
        internal static string roadmapLabel {
            get {
                return ResourceManager.GetString("roadmapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعلان النتائج.
        /// </summary>
        internal static string roadmapLabel1 {
            get {
                return ResourceManager.GetString("roadmapLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رحلة الهاكاثون.
        /// </summary>
        internal static string roadmapTitle {
            get {
                return ResourceManager.GetString("roadmapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثواني.
        /// </summary>
        internal static string secondsCounter {
            get {
                return ResourceManager.GetString("secondsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صنـاعـــــــة وحيـــــــاة.
        /// </summary>
        internal static string slogen {
            get {
                return ResourceManager.GetString("slogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البتروكيماويات.
        /// </summary>
        internal static string target1 {
            get {
                return ResourceManager.GetString("target1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التنقيب.
        /// </summary>
        internal static string target2 {
            get {
                return ResourceManager.GetString("target2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصناعات الخفيفه والثقيلة.
        /// </summary>
        internal static string target3 {
            get {
                return ResourceManager.GetString("target3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الصناعات بالهيئة الملكية بينبع.
        /// </summary>
        internal static string target4 {
            get {
                return ResourceManager.GetString("target4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات المستهدفة.
        /// </summary>
        internal static string targetTitle {
            get {
                return ResourceManager.GetString("targetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كفاءة الطاقة.
        /// </summary>
        internal static string track1 {
            get {
                return ResourceManager.GetString("track1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة النفايات.
        /// </summary>
        internal static string track2 {
            get {
                return ResourceManager.GetString("track2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معالجة المياه.
        /// </summary>
        internal static string track3 {
            get {
                return ResourceManager.GetString("track3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسارات الهاكاثون.
        /// </summary>
        internal static string tracksTitle {
            get {
                return ResourceManager.GetString("tracksTitle", resourceCulture);
            }
        }
    }
}
